package com.my.blog.website.model.Vo;

public class RoleVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_roles.rid
     *
     * @mbg.generated
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_roles.roleName
     *
     * @mbg.generated
     */
    private String rolename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_roles.rid
     *
     * @return the value of t_roles.rid
     * @mbg.generated
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_roles.rid
     *
     * @param rid the value for t_roles.rid
     * @mbg.generated
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_roles.roleName
     *
     * @return the value of t_roles.roleName
     * @mbg.generated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_roles.roleName
     *
     * @param rolename the value for t_roles.roleName
     * @mbg.generated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }
}
