package com.my.blog.website.model.Vo;

public class UserRoleVoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users_roles.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users_roles.rid
     *
     * @mbg.generated
     */
    private Integer rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users_roles.uid
     *
     * @return the value of t_users_roles.uid
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users_roles.uid
     *
     * @param uid the value for t_users_roles.uid
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users_roles.rid
     *
     * @return the value of t_users_roles.rid
     * @mbg.generated
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users_roles.rid
     *
     * @param rid the value for t_users_roles.rid
     * @mbg.generated
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }
}
