package com.my.blog.website.dao;

import com.my.blog.website.model.Vo.UserRoleVoExample;
import com.my.blog.website.model.Vo.UserRoleVoKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserRoleVoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users_roles
     *
     * @mbg.generated
     */
    long countByExample(UserRoleVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users_roles
     *
     * @mbg.generated
     */
    int deleteByExample(UserRoleVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users_roles
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(UserRoleVoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users_roles
     *
     * @mbg.generated
     */
    int insert(UserRoleVoKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users_roles
     *
     * @mbg.generated
     */
    int insertSelective(UserRoleVoKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users_roles
     *
     * @mbg.generated
     */
    List<UserRoleVoKey> selectByExample(UserRoleVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users_roles
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserRoleVoKey record, @Param("example") UserRoleVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users_roles
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserRoleVoKey record, @Param("example") UserRoleVoExample example);
}
